version: '3.7'
services:
  nextjs:
    container_name: ps5-kudasai-form
    build: .
    command: yarn dev
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    tty: true
    restart: always
